##############################
## 4gekkman/docker-node-dev ##
##############################
## Оглавление
##  
##  1. Базовый образ и разработчики
##  2. Установить bower и gulp глобально
##  3. Запустить node
##

# 1. Базовый образ и разработчики
FROM node:latest
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Установить bower и gulp глобально
RUN npm install -g gulp 
RUN npm install -g bower

# 3. Запустить node
CMD [ "node" ]
