##############################
## 4gekkman/docker-node-dev ##
##############################
## Оглавление
##  
##  1. Базовый образ и разработчики
##  2. Установить bower и gulp глобально
##

# 1. Базовый образ и разработчики
FROM node:latest
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. Установить bower и gulp глобально
RUN npm install -g gulp 
RUN npm install -g bower

# 3. Установить необходимые пакеты
RUN apt-get update && apt-get install -y \

    curl \
    cron \
    supervisor
    
# 4. Создать следующие каталоги, если они отсутствуют    
RUN mkdir -p /var/log/supervisor

# 5. Назначить cmd по умолчанию, запускающую supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor.d/supervisor.ini"]

