##############################
## 4gekkman/docker-node-dev ##
##############################
## Ћглавление
##  
##  1. Ѓазовый образ и разработчики
##  2. “становить bower и gulp глобально
##

# 1. Ѓазовый образ и разработчики
FROM node:latest
MAINTAINER German Manvelov <4gekkman@gmail.com>

# 2. “становить bower и gulp глобально
RUN npm install -g gulp 
RUN npm install -g bower

